default_settings: null
behaviors:
  DroneAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512         # Reduced for more stable updates
      buffer_size: 25600      # Reduced accordingly  
      learning_rate: 0.0001   # Lower for more stable learning
      beta: 0.001             # Lower for more stable policy updates
      epsilon: 0.15           # Slightly lower for less aggressive updates
      lambd: 0.95
      num_epoch: 3
      shared_critic: false
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256       # Smaller network, easier to train
      num_layers: 2           # Simpler network
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.995          # Slightly higher discount for navigation
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128   # Smaller critic network
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 25000
    max_steps: 3000000        # Reduced for focused training
    time_horizon: 512         # Longer episodes for navigation
    summary_freq: 2500        # More frequent summaries
    threaded: false
    self_play: null
    behavioral_cloning: null
env_settings:
  env_path: null
  env_args: null
  base_port: 5005
  num_envs: 1
  num_areas: 1
  seed: 42
  max_lifetime_restarts: 10
  restarts_rate_limit_n: 1
  restarts_rate_limit_period_s: 60
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 4.0           # Reduced for more stable physics
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
checkpoint_settings:
  run_id: improved_drone_training
  initialize_from: null
  load_model: false
  resume: false
  force: false
  train_model: false
  inference: false
  results_dir: results
torch_settings:
  device: null
debug: false
environment_parameters:
  stage: 7
