behaviors:
  DroneAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 40960
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 128
    summary_freq: 10000
  # Removed 'threaded' and 'self_play' (invalid here in ML-Agents 0.30.0). Defaults apply.
environment_parameters:
  difficulty:
    curriculum:
      - name: easy
        completion_criteria:
          measure: reward
          behavior: DroneAgent
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 0.2
        value: 0.0
      - name: medium
        completion_criteria:
          measure: reward
          behavior: DroneAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.4
        value: 0.5
      - name: hard
        completion_criteria:
          measure: reward
          behavior: DroneAgent
          signal_smoothing: true
          min_lesson_length: 150
          threshold: 0.6
        value: 1.0
